# Generated by Django 5.1.1 on 2024-09-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('1', 'Perro'), ('2', 'Gato')], default='1', max_length=1)),
                ('estado', models.CharField(choices=[('1', 'Adoptado'), ('2', 'En adopción'), ('3', 'En espera de adopción')], default='3', max_length=1)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
    ]
