# Generated by Django 5.1.1 on 2024-09-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_estado_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('1', 'Voluntario'), ('2', 'Adoptante')], max_length=1),
        ),
    ]
