# Generated by Django 5.1.1 on 2024-09-07 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0002_animales_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Finalizado'), ('2', 'En proceso'), ('3', 'Cancelado')], default='2', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adoptante', models.ForeignKey(limit_choices_to={'tipo': '2'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopciones_adoptante', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones_animal', to='animales.animales')),
                ('voluntario', models.ForeignKey(limit_choices_to={'tipo': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopciones_voluntario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adopcion',
                'verbose_name_plural': 'Adopciones',
            },
        ),
    ]
